### ISSUE TITLE
License

### ISSUE THREAD

**Issue by TechnologyClassroom** [krmaxwell/coding-entertainment#113]
I see you are using a custom license with the phrase: "NOTE: This list is in the public domain but I would appreciate a link back or at least a mention of where you got it if you repost it someplace."

I believe you are looking for CC BY-SA 4.0.  [Here is an example](https://github.com/TechnologyClassroom/RaspberryPiProgrammingWorkshop/blob/master/LICENSE.md) of using this license on github.

**Comment by krmaxwell** [comment]
There is a [LICENSE](https://github.com/krmaxwell/coding-entertainment/blob/master/LICENSE) file specifically releasing this in the public domain; I opted against BY-SA.
